name 'haproxy'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures HAProxy.'
long_description 'Application cookbook which installs and configures HAProxy.'
version '1.0.0'
source_url 'https://github.com/johnbellone/haproxy-cookbook'
issues_url 'https://github.com/johnbellone/haproxy-cookbook/issues'

supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 5.8'
supports 'centos', '>= 5.8'

depends 'cpu', '~> 0.2'
depends 'firewall', '~> 2.0'
depends 'poise', '~> 2.2'
depends 'poise-service', '~> 1.0'
depends 'sysctl', '~> 0.6'
